# fly.toml app configuration file generated for every-student-db on 2026-02-09T10:08:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'every-student-db'
primary_region = 'ewr'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  DATABASE_URL = 'sqlite:////data/student.db'

[[mounts]]
  source = 'student_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
